name: QA checks

on:
  pull_request:
    branches:
      - main

jobs:
  qa:
    name: Check and Build source files
    runs-on: [self-hosted, Linux]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v5
        with:
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check (typecheck + test + lint + prettier)
        run: pnpm run check

      - name: Build package
        run: pnpm run build
